set +e

stack build --resolver lts-2.0
stack build --resolver lts-3.0
stack build --resolver lts-4.0
stack build --resolver lts-5.0
stack build --resolver lts-6.0
stack build --resolver lts-7.0
stack build --resolver lts-7.1
stack build --resolver lts-7.2
stack build --resolver lts-7.3
stack build --resolver lts-7.4
stack build --resolver lts-7.5
stack build --resolver lts-7.6
stack build --resolver lts-7.7
stack build --resolver lts-7.8
stack build --resolver lts-7.9
stack build --resolver lts-7.10
stack build --resolver lts-7.11
stack build --resolver lts-7.12
stack build --resolver lts-7.13
stack build --resolver lts-7.14
stack build --resolver lts-7.15
stack build --resolver lts-7.16
stack build --resolver lts-8.0
stack build --resolver lts-8.1
stack build --resolver lts-8.2
stack build --resolver lts-8.3
stack build --resolver lts-8.4
stack build --resolver lts-8.5
stack build --resolver lts-8.6
stack build --resolver lts-8.7
stack build --resolver lts-8.8
stack build --resolver lts-8.9
stack build --resolver lts-8.10
stack build --resolver lts-8.11
stack build --resolver lts-8.12
stack build --resolver lts-8.13
stack build --resolver lts-9.0
stack build --resolver lts-9.1
stack build --resolver lts-9.2
stack build --resolver lts-9.3
stack build --resolver lts-9.4
stack build --resolver lts-9.5
stack build --resolver lts-9.6
stack build --resolver lts-9.7
stack build --resolver lts-9.8
stack build --resolver lts-9.9
stack build --resolver lts-9.10
stack build --resolver lts-9.11
stack build --resolver lts-9.12
stack build --resolver lts-9.13
stack build --resolver lts-9.14
stack build --resolver lts-9.15
stack build --resolver lts-9.16
stack build --resolver lts-9.17
stack build --resolver lts-9.18
stack build --resolver lts-9.19
stack build --resolver lts-9.20
stack build --resolver lts-10.0
stack build --resolver lts-10.1
stack build --resolver lts-10.2
