name: HLint CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/hlint.yml'
      - 'app/**/*.hs'
      - 'src/**/*.hs'
      - 'test/**/*.hs'
jobs:
  hlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HLINT_ACTION_LOG_LEVEL: debug
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up HLint
        uses: rwe/actions-hlint-setup@v1

      - name: Haskell Lint
        uses: rwe/actions-hlint-run@v2
        with:
          path: '["src/"]'
          fail-on: warning
