name: Nix CI

on: [pull_request]
jobs:
  build:
    name: nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v3
        env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - run: nix-build
